### PR TITLE
Update to Scala 2.12, Play 2.7.0

### PR DESCRIPTION
**Pull request by kojustin**
Updates rules to work with Scala 2.12, and Play 2.7.0.

- Remove StaticRoutesGenerator, that route generation method was removed
  in play 2.7 (https://github.com/playframework/playframework/issues/8047).
- Fix tests to not use FakeApplication, which was removed
  (https://github.com/playframework/playframework/issues/5549).
- Fix the documentation generator.

### CODE REVIEW

**Comment by thundergolfer** [comment]
@kojustin Thanks for the submission. 

I just tried this branch in our `2_11` Bazel workspace, and it predictably doesn't work. I then took your branch and tried this in `dependencies.yaml`: 

`languages: ["scala:2.12.8", "scala:2.11.12"]`

That also predictably doesn't work (`bazel-deps`) just ignores the second lang version listed. I'd expect that `bazel-deps` doesn't support having both Scala majors versions. It'd have to put `select()` rules everywhere or something. 

Do you think this should just keep a `2_11` branch and a `2_12` branch?

**Comment by kojustin** [comment]
I would prefer 2.12, but the real reason I care what Scala version `rules_play_routes` is using is because if you integrate this with your dependent project the naive way (by adding a `local_repository`, `new_http_repository`, etc. onto this project) you need to re-declare the Scala dependency that `rules_play_routes` has otherwise it will fail with missing externals.

If there was a way make this work in a way that doesn't expose the internal Scala version to consumers that would be ideal. For example, https://github.com/bazelbuild/rules_jvm_external includes coursier directly in the repository in source control (https://github.com/bazelbuild/rules_jvm_external/blob/master/third_party/coursier/coursier) so they don't have external dependencies. Maybe packaging up the routes compiler into a deploy jar and creating a Github Release would be the right thing to do .

**Comment by kojustin** [comment]
Skydoc fixes the issue by having consumer projects re-declare all of their dependencies.
https://skydoc.bazel.build/docs/getting_started_stardoc.html

**Comment by thundergolfer** [comment]
>  you need to re-declare the Scala dependency that rules_play_routes has otherwise it will fail with missing externals.

Yes, exactly. It's not great. 

Thanks for linking those examples. I'll get this sorted out.

**Pull request closed without merging**
